// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MediaItemKind.
const (
	Image MediaItemKind = "image"
	Video MediaItemKind = "video"
)

// Valid indicates whether the value is a known member of the MediaItemKind enum.
func (e MediaItemKind) Valid() bool {
	switch e {
	case Image:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for TaskItemStatus.
const (
	Canceled  TaskItemStatus = "canceled"
	Failed    TaskItemStatus = "failed"
	Pending   TaskItemStatus = "pending"
	Running   TaskItemStatus = "running"
	Succeeded TaskItemStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the TaskItemStatus enum.
func (e TaskItemStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Example: INVALID_INPUT
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Username string `json:"username"`
}

// MediaItem defines model for MediaItem.
type MediaItem struct {
	CreatedAt       time.Time     `json:"created_at"`
	DurationSeconds float32       `json:"duration_seconds"`
	Id              string        `json:"id"`
	Kind            MediaItemKind `json:"kind"`
	SpaceId         string        `json:"space_id"`
	Title           string        `json:"title"`
}

// MediaItemKind defines model for MediaItem.Kind.
type MediaItemKind string

// MediaPage defines model for MediaPage.
type MediaPage struct {
	Items    []MediaItem `json:"items"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
	Total    int         `json:"total"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	NeedsSetup bool `json:"needs_setup"`
}

// TaskItem defines model for TaskItem.
type TaskItem struct {
	CreatedAt time.Time `json:"created_at"`
	Error     *string   `json:"error,omitempty"`
	Id        string    `json:"id"`
	Priority  int       `json:"priority"`
	Progress  float32   `json:"progress"`
	SpaceId   *string   `json:"space_id"`

	// Status ADR-0055；client 兼容 completed→succeeded、error→failed
	Status    TaskItemStatus `json:"status"`
	Type      string         `json:"type"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// TaskItemStatus ADR-0055；client 兼容 completed→succeeded、error→failed
type TaskItemStatus string

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// SpaceIdHeader defines model for SpaceIdHeader.
type SpaceIdHeader = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListMediaV2Params defines parameters for ListMediaV2.
type ListMediaV2Params struct {
	Page     *PageParam     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// XJianVideoSpaceId 当前 Space；缺省为 space-default（FR2-007）
	XJianVideoSpaceId *SpaceIdHeader `json:"X-JianVideo-Space-Id,omitempty"`
}

// GetMediaV2Params defines parameters for GetMediaV2.
type GetMediaV2Params struct {
	// XJianVideoSpaceId 当前 Space；缺省为 space-default（FR2-007）
	XJianVideoSpaceId *SpaceIdHeader `json:"X-JianVideo-Space-Id,omitempty"`
}

// GetTaskV2Params defines parameters for GetTaskV2.
type GetTaskV2Params struct {
	// XJianVideoSpaceId 当前 Space；缺省为 space-default（FR2-007）
	XJianVideoSpaceId *SpaceIdHeader `json:"X-JianVideo-Space-Id,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetupJSONRequestBody defines body for Setup for application/json ContentType.
type SetupJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 用户名 + 口令登录
	// (POST /api/auth/login)
	Login(c *gin.Context)
	// Logout 登出当前会话
	// (POST /api/auth/logout)
	Logout(c *gin.Context)
	// Setup 首次初始化（仅系统无用户时可用）
	// (POST /api/auth/setup)
	Setup(c *gin.Context)
	// GetSetupStatus 是否需要首次初始化
	// (GET /api/auth/setup-status)
	GetSetupStatus(c *gin.Context)
	// ListMediaV2 分页列出当前 Space 媒体（v2）
	// (GET /api/v2/media)
	ListMediaV2(c *gin.Context, params ListMediaV2Params)
	// GetMediaV2 媒体详情（v2）
	// (GET /api/v2/media/{id})
	GetMediaV2(c *gin.Context, id string, params GetMediaV2Params)
	// GetTaskV2 任务详情（v2）
	// (GET /api/v2/tasks/{id})
	GetTaskV2(c *gin.Context, id string, params GetTaskV2Params)
	// GetHealth 存活探针
	// (GET /health)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// Setup operation middleware
func (siw *ServerInterfaceWrapper) Setup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Setup(c)
}

// GetSetupStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSetupStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSetupStatus(c)
}

// ListMediaV2 operation middleware
func (siw *ServerInterfaceWrapper) ListMediaV2(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMediaV2Params

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "X-JianVideo-Space-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-JianVideo-Space-Id")]; found {
		var XJianVideoSpaceId SpaceIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-JianVideo-Space-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-JianVideo-Space-Id", valueList[0], &XJianVideoSpaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-JianVideo-Space-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XJianVideoSpaceId = &XJianVideoSpaceId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMediaV2(c, params)
}

// GetMediaV2 operation middleware
func (siw *ServerInterfaceWrapper) GetMediaV2(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMediaV2Params

	headers := c.Request.Header

	// ------------- Optional header parameter "X-JianVideo-Space-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-JianVideo-Space-Id")]; found {
		var XJianVideoSpaceId SpaceIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-JianVideo-Space-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-JianVideo-Space-Id", valueList[0], &XJianVideoSpaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-JianVideo-Space-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XJianVideoSpaceId = &XJianVideoSpaceId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMediaV2(c, id, params)
}

// GetTaskV2 operation middleware
func (siw *ServerInterfaceWrapper) GetTaskV2(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTaskV2Params

	headers := c.Request.Header

	// ------------- Optional header parameter "X-JianVideo-Space-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-JianVideo-Space-Id")]; found {
		var XJianVideoSpaceId SpaceIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-JianVideo-Space-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-JianVideo-Space-Id", valueList[0], &XJianVideoSpaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-JianVideo-Space-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XJianVideoSpaceId = &XJianVideoSpaceId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTaskV2(c, id, params)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/api/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/auth/setup-status", wrapper.GetSetupStatus)
	router.POST(options.BaseURL+"/api/auth/setup", wrapper.Setup)
	router.GET(options.BaseURL+"/api/v2/media", wrapper.ListMediaV2)
	router.GET(options.BaseURL+"/api/v2/media/:id", wrapper.GetMediaV2)
	router.GET(options.BaseURL+"/api/v2/tasks/:id", wrapper.GetTaskV2)
}
